### PR TITLE
added light and dark mode

### LINKED ISSUE #45: add dark and light mode button
add a button to switch from light to dark mode and vice versa

### PR DESCRIPTION
**Pull request by shauryag2002**
fix #45 
i have added toggle button for light and dark mode.

### CODE REVIEW

**Review by Arman-ali-khan-786 — CHANGES_REQUESTED** [review]
add proper comment in js file ok

**Review by shauryag2002 — COMMENTED** [review]
added comments in js file

**Review by Arman-ali-khan-786 — CHANGES_REQUESTED** [review]
change the button theme its not looking good rest functionality is working ok and update the files and then make a pr again

**Comment by Arman-ali-khan-786** [comment]
this is issue has been resloved ,you can work on another issues

**Pull request closed without merging**
