### PR TITLE
cleared all the issues in website like setting my photo path

### PR DESCRIPTION
**Pull request by SaikiranVoladri**
also fixed responsive section

### CODE REVIEW

**Comment by SaikiranVoladri** [comment]
and please merge it after 11:00 pm cause at that time hactoberfest in India starts

**Comment by SaikiranVoladri** [comment]
successfully cleared issue on setting path to my profile

**Comment by SaikiranVoladri** [comment]
tell me if there are any other conflicts

**Review by Arman-ali-khan-786 — COMMENTED** [review]
it doesn't work

**Comment by SaikiranVoladri** [comment]
hello arman I had cleared all the issues and raised a pull request please merge it. here is proof 
https://saikiranvoladri.github.io/CardUI/

**Pull request closed without merging**
