### PR TITLE
Change the UI of the landing page

### PR DESCRIPTION
**Pull request by abitsalihu**
I changed the UI of the landing page to something more modern and minimalistic, I made the `nav bar` in a similar gradient to the scroll bar and text aligned everything on the center so the flow of the website does not break with the rest of the content.

Below are two videos, one is before and one is after my code:

`After:`

https://user-images.githubusercontent.com/94648837/194672994-aa5c21a4-57e1-43b3-88d1-601edb936644.mov

`Before:`

https://user-images.githubusercontent.com/94648837/194673101-5ffcfee6-4be4-4237-855b-424d3583c80c.mov

### CODE REVIEW

**Review by Arman-ali-khan-786 — CHANGES_REQUESTED** [review]
looks awesome , fetch latest changes a do a pr again ok

**Review by Arman-ali-khan-786 — CHANGES_REQUESTED** [review]
see ui-11 is overlapping fix it

**Comment by abitsalihu** [comment]
So i should fetch the latest changes again and then do a pr?

**Comment by abitsalihu** [comment]
Finished

**Comment by abitsalihu** [comment]
@Arman-ali-khan-786 will this be merged or not?

**Review by Arman-ali-khan-786 — CHANGES_REQUESTED** [review]
do you check your work or not ,see ui 10 and 11 bcz center alignment and other changes you have made their ui is distorted , please go through our code make it right then make a pr ok

**Pull request closed without merging**
