### PR TITLE
Fixed some bugs & Added my card.

### PR DESCRIPTION
**Pull request by Kotak-Prerit**
separated all the cards using border bottom. fixed the ui-7 image error. also try to ignore cookies if you can. Do check out my card.

### CODE REVIEW

**Review by Arman-ali-khan-786 — CHANGES_REQUESTED** [review]
remove the lines(border bottom) between cards and follow the website format like you have to write "click here for code *star " so make the required change and do a pr again

**Comment by Kotak-Prerit** [comment]
Yeah sure, but there's one more issue, in ui-7 card the card is above
navbar when we scroll down. So I'm giving navbar z-index more than the ui-7
card. Is that okay?

**Comment by Kotak-Prerit** [comment]
hey bro can you please accept my merge request?

**Review by Arman-ali-khan-786 — CHANGES_REQUESTED** [review]
why you have change readme.md file plus you made unneccessary changes that was not required you just have to add your card code okk

**Pull request closed without merging**
