### PR TITLE
saikiran

### PR DESCRIPTION
**Pull request by SaikiranVoladri**
hello, I had added my card code

### CODE REVIEW

**Comment by SaikiranVoladri** [comment]
successfully worked withour conflicts

**Review by Arman-ali-khan-786 — CHANGES_REQUESTED** [review]
cards looks awesome but you have to write your code(html/css) in given format and if you are adding js code write it in index.js file in the given format okk and one more thing if you are adding your code for card then do not change anything else like header,footer n all...

Do the necessary changes as requested..

**Comment by SaikiranVoladri** [comment]
okay

**Comment by SaikiranVoladri** [comment]
Hey bro i had changed the code according to the syntax of html css and js
as you requested
Once check it  and let me know

**Review by Arman-ali-khan-786 — APPROVED** [review]
well done

**Pull request merged**
