### PR TITLE
Add files in index.html and index.css

### PR DESCRIPTION
**Pull request by hs-07**
Added my Card.UI and made it responsive

### CODE REVIEW

**Comment by hs-07** [comment]
@Arman-ali-khan-786  achaa okk....i didnt noticed the format...

**Comment by hs-07** [comment]
but u can merge it in main as everything is compatible. I had runned it in my localhost...everything looks perfect
@Arman-ali-khan-786

**Comment by Arman-ali-khan-786** [comment]
> but u can merge it in main as everything is compatible. I had runned it in my localhost...everything looks perfect @Arman-ali-khan-786

yeah i can but there's a format for everything you have to follow that it is looking good i agree but all other contributors have done the same

**Comment by hs-07** [comment]
okk i will make it in the same format @Arman-ali-khan-786

**Pull request closed without merging**
