### PR TITLE
feat: added card ui 13

### PR DESCRIPTION
**Pull request by ManuCoutinho**
Created card UI 13

### CODE REVIEW

**Review by Arman-ali-khan-786 — CHANGES_REQUESTED** [review]
see properly you have change ui-12's  code

**Comment by ManuCoutinho** [comment]
Thats was fixed! thks

**Review by Arman-ali-khan-786 — APPROVED** [review]
looks good now

**Review by Arman-ali-khan-786 — APPROVED** [review]
looks good now

**Pull request merged**
